set nocompatible              " be iMproved, required
filetype off                  " required
call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdtree'
Plug 'xuyuanp/nerdtree-git-plugin'
Plug 'tpope/vim-surround'
Plug 'raimondi/delimitmate'
Plug 'bling/vim-airline'
Plug 'tikhomirov/vim-glsl'
Plug 'majutsushi/tagbar'
Plug 'ajh17/vimcompletesme'
Plug 'alvan/vim-closetag'
Plug 'tpope/vim-commentary'
Plug 'octol/vim-cpp-enhanced-highlight'
Plug 'tpope/vim-fugitive'
Plug 'mhinz/vim-startify'
Plug 'SirVer/ultisnips'
Plug 'w0rp/ale'
Plug 'junegunn/fzf'
Plug 'ctrlpvim/ctrlp.vim'
" All of your Plugs must be added before the following line
call plug#end()            " required
""""""""""Vim config""""""""""
    syntax on
    color ez 
    set cursorline
    set background=light
    filetype plugin indent on    " required
    filetype plugin on
    "matching braces color
    highlight MatchParen cterm=bold ctermfg=cyan
    "makes backspace work like most other apps
    set backspace=indent,eol,start
    "Set color for column 100th
    set cc=100
    set encoding=utf-8
    set expandtab
    "Enable switching between tabs without saving
    set foldmethod=manual
    set hidden
    set incsearch
    "Enable line number
    set number
    "identation tab
    set shiftwidth=4
    "makes the backspace key treat the spaces like a tab
    set softtabstop=4
    set tabstop=4
    set termguicolors
    "X11 clipboard
    if has("unix")
        set clipboard=unnamedplus
    elseif has("win32")
        set clipboard=unnamed
    endif
    "window default size
    if has('gui_running')
        set columns=100
    endif
    "Color scheme
    if has("unix")
        set t_8f=[38;2;%lu;%lu;%lum
        set t_8b=[48;2;%lu;%lu;%lum
    endif

    "set gui font
    if has('gui_running')
        if has("unix")
            set guifont=DejaVu\ Sans\ Mono\ 12
        elseif has("win32")
            set guifont=Consolas:h12:cANSI
        endif
        set guioptions-=L
        set guioptions-=m
        set guioptions-=r
        set guioptions-=T
    endif

    " Shortcuts
        " Switch between buffers
        :nnoremap <M-o> :b#<CR>
        " Press Space to turn off highlighting and clear any message already displayed.
        :noremap <Space> :set hlsearch! hlsearch?<CR>
        "map Ctrl-S to save
        noremap <silent> <C-s>          :update<CR>
        vnoremap <silent> <C-s>         <C-C>:update<CR>
        inoremap <silent> <C-s>         <C-O>:update<CR>
        "Set Leader key
        let mapleader="\<Space>"
        nmap <leader>e :e<Space>
        nmap <leader>s :b<Space>
        nmap <leader>q :bd<CR>
        nmap <leader>h <C-W>h<CR>
        nmap <leader>j <C-W>j<CR>
        nmap <leader>k <C-W>k<CR>
        nmap <leader>l <C-W>l<CR>
        
""""""""""nerdtree""""""""""
    " Toggle nerdtree
    nnoremap <F7> :NERDTreeToggle<CR>

""""""""""tagbar""""""""""
    if (has("win32"))
        let g:tagbar_ctags_bin = "$HOME/myconfig/windows/ctags/ctags.exe"
    endif
    nmap <F8> :TagbarToggle<CR>

""""""""""utilsnips""""""""""
    let g:UltiSnipsExpandTrigger="<c-k>"
    let g:UltiSnipsJumpBackwardTrigger="<c-j>"
    let g:UltiSnipsJumpForwardTrigger="<c-k>"

""""""""""vim-airline""""""""""
    "vim-airline always show
    set laststatus=2

""""""""""vim-indent-guides""""""""""
    let g:indent_guides_enable_on_vim_startup = 1

""""""""""ctrlp""""""""""
    :nnoremap <M-l> :CtrlPBuffer<CR>
