set nocompatible              " be iMproved, required
filetype off                  " required
call plug#begin('$VIMRUNTIME/plugged')
Plug 'scrooloose/nerdtree'
Plug 'xuyuanp/nerdtree-git-plugin'
Plug 'morhetz/gruvbox'
"The plugin provides mappings to easily delete, change and add such surroundings in pairs
Plug 'tpope/vim-surround'
"auto closing quotes,...
Plug 'raimondi/delimitmate'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'scrooloose/syntastic'
"status bar
Plug 'bling/vim-airline'
Plug 'tikhomirov/vim-glsl'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'majutsushi/tagbar'
Plug 'ajh17/vimcompletesme'
"html auto-close tag
Plug 'alvan/vim-closetag'
"comment stuff out
Plug 'tpope/vim-commentary'
Plug 'octol/vim-cpp-enhanced-highlight'
Plug 'tpope/vim-fugitive'
Plug 'mhinz/vim-startify'
" All of your Plugs must be added before the following line
call plug#end()            " required
""""""""""Vim config""""""""""
    "Enable syntax highlighting
    syntax enable
    "Enable line number
    set number
    filetype plugin on
    filetype plugin indent on    " required
    "X11 clipboard
    if has("unix")
        set clipboard=unnamedplus
    elseif has("win32")
        set clipboard=unnamed
    endif
    set expandtab
    set tabstop=4
    "identation tab
    set shiftwidth=4
    "makes the backspace key treat the spaces like a tab
    set softtabstop=4
    "makes backspace work like most other apps
    set backspace=indent,eol,start
    "Set color for column 100th
    set cc=100
    "Color scheme
    set termguicolors
    let g:gruvbox_contrast_dark="hard"
    set background=dark
    "Filetype config
    colorscheme gruvbox
    set softtabstop=4
    set encoding=utf-8
    "matching braces color
    highlight MatchParen cterm=bold ctermfg=cyan

    "set gui font
    if has('gui_running')
        if has("unix")
            set guifont=DejaVu\ Sans\ Mono\ Bold\ 12
        elseif has("win32")
            set guifont=Consolas:h12:b:cANSI
        endif
    endif

    " Shortcuts
        " Switch between buffers
        :nnoremap <Tab> :bnext<CR>
        :nnoremap <S-Tab> :bprevious<CR>
        " Press Space to turn off highlighting and clear any message already displayed.
        :nnoremap <silent> <Space> :nohlsearch<Bar>:echo<CR>
        "map Ctrl-S to save
        noremap <silent> <C-s>          :update<CR>
        vnoremap <silent> <C-s>         <C-C>:update<CR>
        inoremap <silent> <C-s>         <C-O>:update<CR>
        "Set Leader key
        let mapleader="\<Space>"
        nnoremap <Leader>w :w<CR>

""""""""""nerdtree""""""""""
    " Toggle nerdtree
    nnoremap <F7> :NERDTreeToggle<CR>

""""""""""tagbar""""""""""
    if (has("win32"))
        let g:tagbar_ctags_bin = "$HOME/myconfig/vim/ctags58/ctags.exe"
    endif
    nmap <F8> :TagbarToggle<CR>

""""""""""vim-airline""""""""""
    "vim-airline always show
    set laststatus=2
    "show buffers list on the top of window
    let g:airline#extensions#tabline#enabled = 1

""""""""""syntastic""""""""""
    "syntastic syntax checking
    set statusline+=%#warningmsg#
    set statusline+=%{SyntasticStatuslineFlag()}
    set statusline+=%*
    let g:syntastic_always_populate_loc_list = 0
    let g:syntastic_auto_loc_list = 1
    let g:syntastic_check_on_wq = 0
    let g:syntastic_cpp_checkers = ['clang_check']
    noremap <F9> :SyntasticCheck<CR>

""""""""""vim-indent-guides""""""""""
    let g:indent_guides_enable_on_vim_startup = 1
